variable "resource_group_name" {}
variable "location" {}
variable "db_secondary_location" {}
variable environment {}
variable "costcenter_id" {}
variable "project_name" {}
variable "vnet_name" {}
variable "vnet_address_space" {}
variable app_subnet {}
variable app_subnet_prefix {}
variable db_subnet {}
variable db_subnet_prefix {}
variable gateway_subnet {}
variable gateway_subnet_prefix {}
variable db_server_name01 {}
variable db_server_name02 {} 
variable "db_name" {}
variable db_version {}
variable db_admin_login {}
variable db_admin_pass {}
variable "storage_alert_emailid" {}
